# active mq
spring:
  jms:
    cache:
      enabled: false
  activemq:
    broker-url: tcp://192.168.248.131:61616
    user: admin
    password: admin123
    pool:
      enabled: true
      # 连接池最大连接数
      max-connections: 10
      # 空闲的连接过期时间，默认为30秒
      idle-timeout: 0